version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: taskmanager

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - DB_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=123123123123
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    command: "node server.js"

  task-service:
    build:
      context: ./backend/task-service
      dockerfile: Dockerfile
    container_name: task-service
    environment:
      - DB_URI=mongodb://mongo:27017/taskdb
      - JWT_SECRET=123123123123
    depends_on:
      - mongo
    ports:
      - "5001:5001"
    command: "node server.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_AUTH_API_URL=http://auth-service:5000/auth
      - REACT_APP_TASK_API_URL=http://task-service:5001/tasks
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - task-service
    command: "npm start"

volumes:
  mongo-data:
    driver: local
