apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: geco97/auth-service:latest  # Make sure this is the correct path to your image
          ports:
            - containerPort: 5000
          env:
            - name: DB_URI
              value: "mongodb://mongo:27017/auth"  # Ensure this points to the MongoDB service name
            - name: JWT_SECRET
              value: "123123123123"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000
  selector:
    app: auth-service
