apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: geco97/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_AUTH_API_URL
          value: "http://localhost:31000"
        - name: REACT_APP_TASK_API_URL
          value: "http://localhost:31001"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000 
  selector:
    app: frontend
